day19_disassembled: day19_disassembled.c
	gcc -std=c99 -Wall -Wextra -O2 -march=native day19_disassembled.c -o day19_disassembled && ./day19_disassembled

day19_human_readable: day19_human_readable.c
	gcc -std=c99 -Wall -Wextra -O2 -march=native day19_human_readable.c -o day19_human_readable && ./day19_human_readable
